sonar.projectKey=FundGaze
sonar.projectName=FundGaze - Fund Raising Website
sonar.projectVersion=1.0

# Source directories
sonar.sources=.
sonar.exclusions=node_modules/**,public/**,views/**,**/*.test.js,**/*.spec.js

# Language
sonar.language=js
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
